name: Deploy to Azure Web App - AppEcommerceAngular

on:
  push:
    branches:
      - khaoula
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ secrets.AZUREAPPSERVICE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AppEcommerceAngular'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      - name: SSH into Azure Web App and execute commands
        uses: azure/ssh-action@v2
        with:
          ssh-endpoint: ${{ secrets.AZURE_SSH_ENDPOINT }}
          script-type: bash
          inline-script: |
            # Commandes à exécuter sur l'App Service après le déploiement
            cd /home/site/wwwroot/AppEcommerceAngular
            npm install
            npm run build
