name: Build and deploy Node.js app to Azure Web App - AppEcommerceAngular

on:
  push:
    branches:
      - khaoula
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: npm install and cache
        run: |
          npm cache clean --force
          npm install --force
          ng build --configuration=production

      - name: Change permissions recursively in source code
        run: chmod -R 777 .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
        
      - name: Change permissions recursively on deployment
        run: chmod -R 777 .

      - name: Set up Node.js version for deployment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: npm cache
        run: npm cache clean --force

      - name: npm install for deployment
        run: npm install --force

      - name: Build Angular app for deployment
        run: ng build --configuration=production

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AppEcommerceAngular'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_804BE8642F274871BB63A5DB00794C24 }}
          package: .
