# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - AppEcommerceAngular

on:
  push:
    branches:
      - khaoula
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: npm install, build, and test
        run: |
          npm cache clean --force
          npm install --force
          npm run build --prod
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: khaoularajhi
          password: ${{ secrets.AZUREAPPSERVICE_DOCKER }}
    
      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ecommerceapp.azurecr.io
          username: ecommerceapp
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINER_REGISTRY }}

      - name: Build and push Docker
        run: |
         docker build --tag=angularproject:latest .
         docker tag angularproject khaoularajhi/angularproject
         docker push khaoularajhi/angularproject

      - name: Push ACR
        run: |
         docker tag angularproject ecommerceapp.azurecr.io/angularproject:latest
         docker push ecommerceapp.azurecr.io/angularproject:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AppEcommerceAngular'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4476875C41A9418D9FA2D7E6E90A25C7 }}
          package: .
